apiVersion: v1
kind: Secret
metadata:
  name: prometheus-secret
type: Opaque
stringData:
  web.yml: |
    basic_auth_users:
      admin: "$2a$12$Cmp7aFwi1N/fZAdJZTVAwevINMrwW6BaNhrMHbNhTTWHoqZ9QYPBS"
