spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: prometheus
          command:
            - "prometheus"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.config.file=/etc/secret/web.yml"
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage
              mountPath: /prometheus
            - name: secret-volume
              mountPath: /etc/secret/
              readOnly: true
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: config-volume
          configMap:
            name: prometheus-config
        - name: secret-volume
          secret:
            secretName: prometheus-secret
