apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus
      image: prom/prometheus:v3.4.1
      command:
        - "prometheus"
        - "--config.file=/etc/prometheus/prometheus.yml"
      ports:
        - containerPort: 9090
  restartPolicy: Always
